### ISSUE TITLE
User Story: Footer

### ISSUE THREAD

**Issue by denham-ed** [denham-ed/rescala-app#27]
As a **site user**, I can **always see a website footer**, in order to **learn key information about the site**.

---
### Acceptance Criteria

1. Footer must appear on every page
2. Footer contains brand and tagline
3. Footer contains links to GitHub and LinkedIn
4. Links should open in new tab

---
### Tasks

- [ ] Create a footer outline
- [ ] Attach the footer to the bottom of page
- [ ] Add 'social' links
